### ISSUE TITLE
felogin / constants for mail address and sender name are swapped

### ISSUE THREAD

**Issue by metiny** [AstCommodore/threeme#10]
Dear Andre, thank you very much for your great work!

I found a small bug in the file \threeme\Configuration\TypoScript\Extensions\FeLogin\constants.txt

Constants for mail address and sender name are swapped:

Line 31 - 35:
emailFrom = {$threeme.frontend.emailFromName}
emailFromName = {$threeme.frontend.emailFromAddress}

Best regards
Metin

Threeme	4.0.0

**Comment by AstCommodore** [comment]
Thank you! :)
