### ISSUE TITLE
media Gallery and Lightbox taking the wrong picture for desktop resolution

### ISSUE THREAD

**Issue by metiny** [AstCommodore/threeme#12]
media Gallery and lightbox in CE's is using maybe the wrong picture (mobil, 1x1) for desktop (> 1200px).

With a iPad, everything work as expected.

**Comment by AstCommodore** [comment]
Hello, could you describe this issue a little bit more detailed? Could I take a look on it?
Which T3 and Threeme version do you use? Anything else on 3rd party extensions?

**Comment by metiny** [comment]
i try it with:
TYPO3 8.7.8
Threeme 4.2.1
no other relevant EXT for pictures, only mask, realurl, news, powermail etc.

I send you a PM with a test page.

**Comment by AstCommodore** [comment]
Hello @metiny ,

maybe today I could take a lock on your site. Maybe it's the same here as I described in issue #13 ?

**Comment by metiny** [comment]
pls. see my answer for issue #13

**Comment by AstCommodore** [comment]
Duplicate to #13

**Comment by AstCommodore** [comment]
Hi @metiny,
the documentaion of fancybox http://fancyapps.com/fancybox/3/docs/#images points out that srcset is supported. 

I tested some new configuration, but I'm not really sure if setting the srcset for fancybox is the right way ...?! It always opens the largest picture, so why I need a "data-srcset" ?! Maybe my config is still buggy ... you could test this one here (rename to .html) ->

[threeme-gallery.txt](https://github.com/AstCommodore/threeme/files/1418271/threeme-gallery.txt)

**Comment by metiny** [comment]
Hello André,
i tested the mediagallery with the new file threeme-gallery.html. 

It works now on desktop, tablet and mobil. You can test it on my site. 
Thank you!
