### ISSUE TITLE
picture scaled incorrectly in tablet landscape resolution

### ISSUE THREAD

**Issue by metiny** [AstCommodore/threeme#13]
Big picture at the homepage (top of the page, threeme-carousel) is scaled incorrectly in tablet landscape resolution. Portrait resolution work as expected.

On desktop everything work as expected.

**Comment by AstCommodore** [comment]
Hello, could you describe this issue a little bit more detailed? Could I take a look on it?
Which T3 and Threeme version do you use? Anything else on 3rd party extensions?

**Comment by metiny** [comment]
Hello André,
thanks for the really incredible work and sorry, I forgot the details of my website:
TYPO3 8.7.8
PHP 7
Threeme 4.2.1
No other relevant EXT for pictures, only mask, realurl, news, powermail etc.

The problem is also visible on the threeme.de website. Also in the simulation e.g. with Chrome in Windows10. 

Try iPad resolution, portrait format (768x1024px), the image is scaled incorrectly, squashed. Caption of the carousel is quite visible. 

iPad, landscape format (1024x786px), text is cropped, image is scaled correctly.

**Comment by AstCommodore** [comment]
Hello @metiny ,

the threeme.de website is not really up to date, I'm sorry ... Did you crop your images for the viewports as you would prefer? Threeme or better TYPO3 couldn't crop the images automatically and so it might be a wrong format for the desired view.

**Comment by metiny** [comment]
Hello André, thank you for your help. 

I have just tested it again: 
normally i have images with 3:2 for desktop view. 

Whether I crop the images for desktopview or not, for Lightbox in desktop view (> 1200) is always the picture for mobile taken (in my case a crop, 1:1) and stretched.

Metin

**Comment by AstCommodore** [comment]
Oh, yeah! I got it. "Fancybox" is used as lightbox lib and it seems fancybox is capturing the wrong image from the picture set. So, on every content element with a picture set and Lightbox will fail. News doesn't use a picture set, so everything is alright!
