### ISSUE TITLE
constant "spamProtectEmailAddresses" does'nt work with option "ascii"

### ISSUE THREAD

**Issue by metiny** [AstCommodore/threeme#14]
Constant 
threeme.enable.spamProtectEmailAddresses = ascii
does'nt work. The mail links are plain text (see threeme.de website).

e.g. 
threeme.enable.spamProtectEmailAddresses = 2
works

**Comment by metiny** [comment]
it has also not worked so. JS to uncryptmailto was not found.

It was the following setting in the constants:
threeme.enable.removeDefaultJS = 1

The following setting works:
threeme.enable.removeDefaultJS = external

Here I found the reference:
http://blog.dirk-helbert.de/blog/2012/01/29/typo3-linkto_uncryptmailto-funktion-wird-nicht-
found/

**Comment by AstCommodore** [comment]
Sry, it works like expected - this is just "standard" TypoScript configuration. Please take a look into the code of threeme.de, don't use the browser's build-in inspectors.

Further more information at https://docs.typo3.org/typo3cms/TyposcriptReference/7.6/Setup/Config/#spamprotectemailaddresses

You could use both, "ascii" or a integer. In case of the integer you have to include the needed JS as you described.

**Comment by metiny** [comment]
Thank you. Have learned something again. 

Maybe as a hint for the documentation, if someone takes instead of ascii another value?

**Comment by AstCommodore** [comment]
Not really, because it's TypoScript and it's well documented. ;) Sry!
