### ISSUE TITLE
navbar, first menu item is never active. blank between css classes active and first is missing

### ISSUE THREAD

**Issue by metiny** [AstCommodore/threeme#15]
navbar, first menu item, if active, have class=activefirst. 
blank space before "first" is missing.

File: threeme/Resources/Private/Fluid/Frontend/Partials/Menus/Navbar.html, LINE 9

`<li id="navlist{menuItem.data.uid}" class="{f:if(condition:'{menuItem.active}', then: 'active')}{f:if(condition: menuIterator.isFirst, then: 'first')}{f:if(condition: menuIterator.isLast, then: ' last')}">`

Threeme 4.2.1

**Comment by AstCommodore** [comment]
Your right, will be fixed in version 4.2.2
