### ISSUE TITLE
threeme 4.2.6 Scrollbar in TYPO3 Backend does not work anymore

### ISSUE THREAD

**Issue by kfumy** [AstCommodore/threeme#17]
Hi I updated an TYPO3 8.7.12 installation with Threeme from 4.2.5 to 4.2.6.
Afterwords the Scrollbar from the Contentblock in the TYPO3 Backend was gone, so content outside my browserwindow is not reachable anymore. I tested it with Safari, Chrome and Firefox on my Mac..., with Threeme 4.2.5 everything works fine.

**Comment by AstCommodore** [comment]
Yes, I implemented a fix for CKEditor only, but in 8.7.12 it's fixed and my change breaks the Backend. Please remove the styles in Resources/Public/Styles/Backend/styles-skin.css targeting the html and body tag.

It will be fixed in the next version. Thanks!
