### ISSUE TITLE
Indexed Search incorrect rendering

### ISSUE THREAD

**Issue by PeetBV** [AstCommodore/threeme#9]
![indexsuche](https://user-images.githubusercontent.com/29895478/27835215-63bf45d2-60da-11e7-891b-cfdba5a7adf6.PNG)

**Comment by PeetBV** [comment]
Hier Source dazu:

<img width="1285" alt="source_indexed" src="https://user-images.githubusercontent.com/29895478/27851173-61e1df7a-6159-11e7-9235-79c0b42e2f7c.PNG">

**Comment by AstCommodore** [comment]
Sry for the delay - have to test it yet. This seems to be a bug in indexed_search not in the Threeme Fluid template ...?!

**Comment by AstCommodore** [comment]
A bug in Threeme ... ;)
